spring.application.name=TamThanhFood
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://sa:sapassword@tonicluster.clcg9ff.mongodb.net/TamThanhFood?retryWrites=true&w=majority}
server.port=8080